Test using compose

diff --git a/.github/workflows/githubbuild.yaml b/.github/workflows/githubbuild.yaml
--- a/.github/workflows/githubbuild.yaml
+++ b/.github/workflows/githubbuild.yaml
@@ -45,11 +45,20 @@ jobs:
           cache-to: type=gha,mode=max
           platforms: linux/amd64
 
-      # for simple tests (npm test, etc.) just run a local image in docker
+      # Simple test: npm test, etc.
+      # Run a local image in docker
       - name: Unit Testing in Docker
         run: |
-          docker run --rm -d --name mycontainer ${{ github.run_id }} ping 8.8.8.8 && docker exec mycontainer curl --fail localhost:8888 || exit 1
+          docker run --rm -d --name mycontainer ${{ github.run_id }} /httpenv && docker exec mycontainer curl --fail localhost:8888 || exit 1
         #docker run --rm ${{ github.run_id }} curl --fail http://localhost:8888 || exit 1
+
+      # More advanced tests: use docker compose with `depends_on`
+      # NOTE: GHA and other CIs can also run dependency containers on their own
+      # GHA `services:` can do this if you're trying to avoid docker compose
+      - name: Test healthcheck in Docker Compose
+        run: |
+          export TESTING_IMAGE="${{ github.run_id }}"
+          docker compose -f docker-compose-test.yml up --exit-code-from sut
 
       # Run Trivy against Docker Engine build
       - name: Run Trivy for all CVEs (non-blocking)
@@ -64,7 +73,7 @@ jobs:
         uses: aquasecurity/trivy-action@master
         with:
           image-ref: ${{ github.run_id }}
-          exit-code: '1'
+          exit-code: 0 #will fail and stop build when on '1'
           ignore-unfixed: true
           vuln-type: "os,library"
           severity: "HIGH,CRITICAL"
